import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useCallback, useEffect, useState } from 'react'
import { AlignCenter, Bold, Bot, ChevronLeft, Download, History, Italic, Link2, MessageSquare, MoreHorizontal, Palette, Redo2, Share2, Undo2, ZoomIn, ZoomOut } from 'lucide-react'
import { AppHeader } from '../components/AppHeader'
import { CanvasGrid } from '../components/CanvasGrid'
import { SheetTabs } from '../components/SheetTabs'
import { VersionPanel } from '../components/VersionPanel'
import { api, address } from '../lib/api'
import { collaborationClientId } from '../lib/client'
import { useCollaborationStore } from '../state/collaboration'
import { cellKey, selectedBounds, useEditorStore } from '../state/editor'
import type { BuildInfo, MutationResult, Session, Sheet, Workbook } from '../types'

export function EditorPage({workbookId,build,session}:{workbookId:string;build?:BuildInfo;session?:Session}) {
  const client=useQueryClient();const workbook=useQuery({queryKey:['workbook',workbookId],queryFn:()=>api<Workbook>(`/api/v1/workbooks/${workbookId}`)})
  const [activeSheet,setActiveSheet]=useState<Sheet|undefined>();const [serverVersion,setServerVersion]=useState(1);const [rightPanel,setRightPanel]=useState<'ai'|'history'|null>('ai')
  const editor=useEditorStore();const editorSelection=selectedBounds(editor);const activeCell=editor.cells.get(cellKey(editor.activeRow,editor.activeColumn));const formula=activeCell?.formula||(activeCell?.value==null?'':String(activeCell.value))
  const connect=useCollaborationStore(state=>state.connect),disconnect=useCollaborationStore(state=>state.disconnect),sendCursor=useCollaborationStore(state=>state.sendCursor),sendSelection=useCollaborationStore(state=>state.sendSelection)
  const collaborationStatus=useCollaborationStore(state=>state.status),collaborators=useCollaborationStore(state=>state.users)
  const updateVersion=useCallback((value:number)=>setServerVersion(current=>Math.max(current,value)),[])
  const handleCollaborationVersion=useCallback((value:number)=>{updateVersion(value);client.invalidateQueries({queryKey:['workbook',workbookId]})},[client,updateVersion,workbookId])
  useEffect(()=>{if(workbook.data){setServerVersion(workbook.data.version);setActiveSheet(current=>current&&workbook.data.sheets.some(sheet=>sheet.id===current.id)?current:workbook.data.sheets[0])}},[workbook.data])
  useEffect(()=>{editor.reset()},[activeSheet?.id])
  useEffect(()=>{connect(workbookId,handleCollaborationVersion);return()=>disconnect()},[connect,disconnect,handleCollaborationVersion,workbookId])
  useEffect(()=>{if(activeSheet&&collaborationStatus==='connected'){sendCursor({sheet_id:activeSheet.id,row:editor.activeRow,column:editor.activeColumn});sendSelection({sheet_id:activeSheet.id,start:{row:editorSelection.startRow,column:editorSelection.startColumn},end:{row:editorSelection.endRow,column:editorSelection.endColumn}})}},[activeSheet,collaborationStatus,sendCursor,sendSelection])
  const nextSheetName=()=>{const used=new Set((workbook.data?.sheets??[]).map(sheet=>sheet.name.toLowerCase()));for(let index=1;;index++){const name=`Sheet${index}`;if(!used.has(name.toLowerCase()))return name}}
  const refreshWorkbook=async()=>client.invalidateQueries({queryKey:['workbook',workbookId]})
  const createSheet=async()=>{const sheet=await api<Sheet>(`/api/v1/workbooks/${workbookId}/sheets`,{method:'POST',body:JSON.stringify({name:nextSheetName()})});setActiveSheet(sheet);await refreshWorkbook()}
  const updateSheet=async(sheet:Sheet,input:Record<string,unknown>)=>{const updated=await api<Sheet>(`/api/v1/sheets/${sheet.id}`,{method:'PATCH',body:JSON.stringify(input)});if(activeSheet?.id===sheet.id)setActiveSheet(updated);await refreshWorkbook()}
  const duplicateSheet=async(sheet:Sheet)=>{const duplicated=await api<Sheet>(`/api/v1/sheets/${sheet.id}/duplicate`,{method:'POST',body:'{}'});setActiveSheet(duplicated);await refreshWorkbook()}
  const deleteSheet=async(sheet:Sheet)=>{const ordered=workbook.data!.sheets;const index=ordered.findIndex(item=>item.id===sheet.id);const fallback=ordered[index===0?1:index-1];await api(`/api/v1/sheets/${sheet.id}`,{method:'DELETE'});if(activeSheet?.id===sheet.id&&fallback)setActiveSheet(fallback);await refreshWorkbook()}
  const revertOperation=async(mode:'undo'|'redo')=>{if(!navigator.onLine){alert('Undo와 Redo는 서버에 다시 연결한 후 사용할 수 있습니다.');return}const target=mode==='undo'?editor.takeUndo():editor.takeRedo();if(!target)return;editor.setSaveState('saving');try{const result=await api<MutationResult>(`/api/v1/operations/${target}:undo`,{method:'POST',body:JSON.stringify({idempotency_key:`undo:${target}`,client_id:collaborationClientId()})});updateVersion(result.server_version);if(result.applied_cells>0){if(mode==='undo')editor.completeUndo(result.operation_id);else editor.completeRedo(result.operation_id)}else{if(mode==='undo')editor.restoreUndo(target);else editor.restoreRedo(target)}editor.setSaveState(result.conflicts.length?'conflict':'saved',result.conflicts.length)}catch{if(mode==='undo')editor.restoreUndo(target);else editor.restoreRedo(target);editor.setSaveState('error')}}
  const exportWorkbook=async(format:'xlsx'|'csv')=>{const response=await fetch('/api/v1/exports',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({workbook_id:workbookId,sheet_id:activeSheet?.id,format})});if(!response.ok)return alert('파일을 내보내지 못했습니다.');const blob=await response.blob();const disposition=response.headers.get('Content-Disposition')||'';const encoded=disposition.match(/filename\*=UTF-8''([^;]+)/)?.[1];const basic=disposition.match(/filename="?([^";]+)"?/)?.[1];const name=encoded?decodeURIComponent(encoded):basic||`kanpic.${format}`;const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();URL.revokeObjectURL(link.href)}
  const handleRestored=async(result:MutationResult)=>{editor.reset();updateVersion(result.server_version);await client.invalidateQueries({queryKey:['workbook',workbookId]})}
  if(workbook.isLoading)return <div className="editor-loading">kanpic 편집기를 준비하는 중…</div>
  if(!workbook.data||!activeSheet)return <div className="editor-loading error">워크북을 찾을 수 없습니다.</div>
  const saveLabel={saved:'모든 변경사항 저장됨',saving:'저장 중…',offline:'오프라인 · 로컬 저장',conflict:`충돌 ${editor.conflicts}건`,error:'저장 오류'}[editor.saveState]
  return <div className="editor-shell"><AppHeader build={build} session={session}><div className="editor-title"><a href="/" aria-label="뒤로"><ChevronLeft/></a><div><strong>{workbook.data.title}</strong><small><span className={`save-dot ${editor.saveState}`}/>{saveLabel} · v{serverVersion}</small></div></div></AppHeader>
    <div className="editor-actions"><div className="menu-strip"><button>파일</button><button>수정</button><button>보기</button><button>삽입</button><button>서식</button><button>데이터</button><button>도구</button></div><div className="share-actions"><span className={`collaboration-count ${collaborationStatus}`} title={Object.values(collaborators).map(user=>user.actor_id).join(', ')}><i/>{collaborationStatus==='connected'?`${Object.keys(collaborators).length}명 접속`:collaborationStatus==='offline'?'오프라인':'재연결 중'}</span><button className="ghost" onClick={()=>exportWorkbook('xlsx')} title="XLSX로 내보내기"><Download/> XLSX 내보내기</button><button className="ghost" onClick={()=>exportWorkbook('csv')} title="현재 시트를 CSV로 내보내기">CSV</button><button className="primary"><Share2/> 공유</button></div></div>
    <div className="toolbar"><button aria-label="실행 취소" title="실행 취소" disabled={editor.undoStack.length===0} onClick={()=>revertOperation('undo')}><Undo2/></button><button aria-label="다시 실행" title="다시 실행" disabled={editor.redoStack.length===0} onClick={()=>revertOperation('redo')}><Redo2/></button><span className="divider"/><button><Bold/></button><button><Italic/></button><button><Palette/></button><span className="divider"/><button><AlignCenter/></button><button><Link2/></button><span className="toolbar-spacer"/><button onClick={()=>editor.setZoom(editor.zoom-.1)}><ZoomOut/></button><span className="zoom-value">{Math.round(editor.zoom*100)}%</span><button onClick={()=>editor.setZoom(editor.zoom+.1)}><ZoomIn/></button><button aria-label="AI 도우미" title="AI 도우미" onClick={()=>setRightPanel(current=>current==='ai'?null:'ai')} className={rightPanel==='ai'?'active':''}><Bot/></button><button aria-label="버전 이력" title="버전 이력" onClick={()=>setRightPanel(current=>current==='history'?null:'history')} className={rightPanel==='history'?'active':''}><History/></button><button><MessageSquare/></button><button><MoreHorizontal/></button></div>
    <div className="formula-bar"><div className="name-box">{editorSelection.startRow===editorSelection.endRow&&editorSelection.startColumn===editorSelection.endColumn?address(editor.activeRow,editor.activeColumn):`${address(editorSelection.startRow,editorSelection.startColumn)}:${address(editorSelection.endRow,editorSelection.endColumn)}`}</div><span>fx</span><input value={formula} readOnly onDoubleClick={()=>editor.setEditing(true)} aria-label="수식 입력창"/></div>
    <div className="editor-body"><div className="sheet-area"><CanvasGrid sheetId={activeSheet.id} version={serverVersion} onVersion={updateVersion}/><SheetTabs sheets={workbook.data.sheets} activeSheetId={activeSheet.id} saveState={editor.saveState} saveLabel={saveLabel} onSelect={setActiveSheet} onCreate={createSheet} onRename={(sheet,name)=>updateSheet(sheet,{name})} onDuplicate={duplicateSheet} onMove={(sheet,position)=>updateSheet(sheet,{position})} onColor={(sheet,color)=>updateSheet(sheet,{color})} onDelete={deleteSheet}/></div>
      {rightPanel==='ai'&&<aside className="ai-panel"><div className="ai-panel-head"><span><Bot/> AI 도우미</span><button onClick={()=>setRightPanel(null)}>×</button></div><div className="ai-intro"><div className="ai-glyph"><Bot/></div><h3>무엇을 도와드릴까요?</h3><p>선택한 범위를 읽고 수식, 정제, 분석 방법을 제안할 수 있어요. 변경은 승인 전까지 적용되지 않습니다.</p></div><div className="suggestion-list"><button>선택 범위의 핵심 지표 요약</button><button>열에 맞는 수식 추천</button><button>데이터 정제 규칙 만들기</button></div><div className="ai-prompt"><textarea placeholder="데이터에 대해 질문하세요…"/><button>↑</button><small>읽기 · 제안 모드</small></div></aside>}
      {rightPanel==='history'&&<VersionPanel workbookId={workbookId} currentVersion={serverVersion} onClose={()=>setRightPanel(null)} onRestored={handleRestored}/>}
    </div>
  </div>
}
