import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useRef, useState } from 'react'
import { Clock3, FilePlus2, FileUp, Grid2X2, MoreHorizontal, Plus, Star, UploadCloud } from 'lucide-react'
import { api, newIdempotencyKey } from '../lib/api'
import type { BuildInfo, Session, Workbook } from '../types'
import { AppHeader } from '../components/AppHeader'

export function HomePage({build,session}:{build?:BuildInfo;session?:Session}) {
  const client=useQueryClient();const [title,setTitle]=useState('');const inputRef=useRef<HTMLInputElement>(null);const [importFile,setImportFile]=useState<File>();const [preview,setPreview]=useState<{format:string;total_cells:number;sheets:Array<{name:string;rows:number;columns:number;non_empty_cells:number}>;warnings:string[]} >();const [importing,setImporting]=useState(false)
  const workbooks=useQuery({queryKey:['workbooks'],queryFn:()=>api<{items:Workbook[]}>('/api/v1/workbooks')})
  const create=useMutation({mutationFn:()=>api<Workbook>('/api/v1/workbooks',{method:'POST',body:JSON.stringify({title:title.trim()||'제목 없는 워크북',workspace_id:'default'})}),onSuccess:(wb)=>{client.invalidateQueries({queryKey:['workbooks']});window.location.href=`/workbooks/${wb.id}`}})
  const chooseImport=async(file?:File)=>{if(!file)return;setImportFile(file);const form=new FormData();form.append('file',file);const result=await api<{format:string;total_cells:number;sheets:Array<{name:string;rows:number;columns:number;non_empty_cells:number}>;warnings:string[]}>('/api/v1/imports:preview',{method:'POST',body:form});setPreview(result)}
  const executeImport=async()=>{if(!importFile)return;setImporting(true);try{const form=new FormData();form.append('file',importFile);form.append('workspace_id','default');const created=await api<Workbook>('/api/v1/imports',{method:'POST',body:form,headers:{'Idempotency-Key':newIdempotencyKey()}});window.location.href=`/workbooks/${created.id}`}finally{setImporting(false)}}
  return <div className="page-shell"><AppHeader build={build} session={session}/><main className="home-content">
    <section className="home-title"><div><span className="eyebrow">WORKSPACE</span><h1>좋은 아침이에요.</h1><p>오늘도 데이터에서 더 나은 답을 만들어 보세요.</p></div><div className="home-title-actions"><input ref={inputRef} type="file" hidden accept=".csv,.tsv,.xlsx" onChange={event=>chooseImport(event.target.files?.[0])}/><button className="secondary" onClick={()=>inputRef.current?.click()}><FileUp size={18}/> 파일 가져오기</button><button className="primary" onClick={()=>create.mutate()}><Plus size={18}/> 새 워크북</button></div></section>
    <section className="quick-start"><div className="section-heading"><h2>빠른 시작</h2></div><div className="template-row">
      <button className="template blank" onClick={()=>create.mutate()}><span><FilePlus2/></span><strong>빈 워크북</strong><small>새로운 데이터 작업 시작</small></button>
      {['프로젝트 현황','월간 매출 분석','업무 요청 관리'].map((name,index)=><button className={`template template-${index}`} key={name} onClick={()=>{setTitle(name);setTimeout(()=>create.mutate(),0)}}><span><Grid2X2/></span><strong>{name}</strong><small>kanpic 기본 템플릿</small></button>)}
    </div></section>
    <section className="recent-section"><div className="section-heading"><h2>최근 워크북</h2><div className="segmented"><button className="active"><Clock3/> 최근</button><button><Star/> 즐겨찾기</button></div></div>
      {workbooks.isLoading?<div className="loading-card">워크북을 불러오는 중…</div>:workbooks.data?.items.length===0?<div className="empty-state"><FilePlus2/><h3>첫 워크북을 만들어 보세요</h3><p>셀 편집 내용은 자동으로 안전하게 저장됩니다.</p></div>:<div className="workbook-grid">{workbooks.data?.items.map(wb=><a href={`/workbooks/${wb.id}`} className="workbook-card" key={wb.id}><div className="workbook-preview"><Grid2X2/><span>{wb.sheets.length} sheets</span></div><div className="workbook-meta"><div><strong>{wb.title}</strong><small>{new Date(wb.updated_at).toLocaleString('ko-KR')} 수정</small></div><button aria-label="더보기"><MoreHorizontal/></button></div></a>)}</div>}
    </section>
    {preview&&importFile&&<div className="modal-backdrop"><div className="modal import-modal"><div className="import-preview-icon"><UploadCloud/></div><h2>{importFile.name}</h2><p>{preview.format.toUpperCase()} · 비어 있지 않은 셀 {preview.total_cells.toLocaleString()}개</p><div className="import-sheet-list">{preview.sheets.map(sheet=><div key={sheet.name}><Grid2X2/><div><strong>{sheet.name}</strong><small>{sheet.rows.toLocaleString()}행 × {sheet.columns.toLocaleString()}열 · {sheet.non_empty_cells.toLocaleString()}개 셀</small></div></div>)}</div>{preview.warnings.length>0&&<div className="import-warnings">{preview.warnings.map(warning=><span key={warning}>{warning}</span>)}</div>}<div className="modal-actions"><button className="secondary" onClick={()=>{setPreview(undefined);setImportFile(undefined)}}>취소</button><button className="primary" disabled={importing} onClick={executeImport}>{importing?'가져오는 중…':'워크북으로 가져오기'}</button></div></div></div>}
  </main></div>
}
