export type BuildInfo = { product: string; version: string; commit: string; build_time: string; go_version: string }
export type AuthConfig = { oidc_enabled:boolean; bootstrap_login_enabled:boolean; issuer_url:string; client_id:string; client_secret_configured:boolean }
export type User = { id: string; email?: string; display_name: string; roles: string[]; expires_at: string }
export type Session = { authenticated: boolean; user?: User; admin?: boolean }
export type DimensionSize = { index:number; size:number }
export type DimensionRange = { start:number; end:number }
export type DimensionGroup = { start:number; end:number; collapsed:boolean; depth:number }
export type CellHistorySnapshot = { value?:unknown; formula?:string; empty:boolean }
export type CellHistoryEntry = { operation_id:string; operation_type:string; actor_id:string; actor_name?:string; server_version:number; before:CellHistorySnapshot; after:CellHistorySnapshot; created_at:string }
export type CellHistory = { sheet_id:string; address:string; items:CellHistoryEntry[] }
export type Connection = { source:string; range:string; workbook_id?:string; title?:string; status:'ok'|'error'; message?:string; rows?:number; columns?:number; cells:string[] }
export type WorkbookConnections = { workbook_id:string; items:Connection[]; checked_at:string; refreshed_at?:string; version?:number }
export type Slicer = { id:string; filter_view_id:string; column:number; title?:string; position:ChartPosition }
export type SheetLayout = { revision:number; row_heights?:DimensionSize[]; column_widths?:DimensionSize[]; hidden_rows?:DimensionRange[]; hidden_columns?:DimensionRange[]; row_groups?:DimensionGroup[]; column_groups?:DimensionGroup[]; frozen_rows:number; frozen_columns:number; slicers?:Slicer[] }
export type Sheet = { id: string; workbook_id: string; name: string; position: number; color?: string; hidden: boolean; layout:SheetLayout; created_at: string }
export type SheetLayoutMutation = { expected_revision:number; idempotency_key:string; client_id?:string; action:'resize'|'reset_size'|'hide'|'show'|'show_all'|'freeze'|'group'|'ungroup'|'collapse'|'expand'|'slicer_add'|'slicer_update'|'slicer_remove'; axis?:'row'|'column'; start?:number; count?:number; size?:number; frozen_rows?:number; frozen_columns?:number; slicer?:Partial<Slicer> }
export type SheetLayoutResult = { operation_id:string; workbook_id:string; sheet_id:string; base_version:number; server_version:number; layout:SheetLayout; duplicate:boolean; created_at:string }
export type AdminOverview = { users:number; active_users:number; suspended_users:number; departments:number; workbooks:number; trashed_workbooks:number; shared_workbooks:number; organization_shared:number; anyone_shared:number; orphan_workbooks:number; pending_access_requests:number; shares:number }
export type GovernedWorkbook = { id:string; title:string; owner_id:string; owner_name?:string; owner_status?:string; link_access:LinkAccess; link_role:ShareRole; share_count:number; sheet_count:number; version:number; updated_at:string; deleted_at?:string; pending_access_requests:number }
export type UserSummary = { user_id:string; display_name?:string; email?:string }
export type DirectoryUser = { user_id:string; display_name?:string; email?:string; status:'active'|'suspended'; note?:string; roles:string[]; departments?:string[]; owned_workbooks:number; created_by?:string; created_at:string; updated_at:string; last_seen_at?:string }
export type SheetStats = { sheet_id:string; name:string; position:number; hidden:boolean; color?:string; non_empty_cells:number; formula_cells:number; max_row:number; max_column:number; updated_at?:string }
export type Workbook = { id: string; workspace_id: string; title: string; owner_id: string; favorite: boolean; version: number; created_at: string; updated_at: string; sheets: Sheet[]; link_access?:LinkAccess; link_role?:ShareRole; sharing_locked?:boolean; viewer_can_copy?:boolean; access_role?:ShareRole; access_source?:AccessSource; shared_count?:number; deleted_at?:string; deleted_by?:string }
export type ShareRole = 'viewer'|'commenter'|'editor'|'owner'
export type LinkAccess = 'restricted'|'organization'|'anyone'
export type AccessSource = 'owner'|'admin'|'user'|'department'|'role'|'link'
export type PrincipalType = 'user'|'department'|'role'
export type WorkbookShare = { id:string; workbook_id:string; principal_type:PrincipalType; principal_id:string; principal_label?:string; role:ShareRole; revision:number; created_by?:string; created_at:string; updated_at:string }
export type WorkbookSharing = { workbook_id:string; owner_id:string; link_access:LinkAccess; link_role:ShareRole; sharing_locked:boolean; viewer_can_copy:boolean; shares:WorkbookShare[] }
export type WorkbookAccess = { workbook_id:string; actor_id:string; role:ShareRole|''; source?:AccessSource; source_label?:string; can_read:boolean; can_comment:boolean; can_write:boolean; can_manage:boolean; can_copy:boolean; link_access:LinkAccess; link_role:ShareRole; owner_id:string }
export type SharingResponse = { sharing:WorkbookSharing; access:WorkbookAccess }
export type Department = { id:string; parent_id?:string; name:string; description?:string; path?:string; depth:number; member_count:number; members?:string[]; revision:number; created_by?:string; created_at:string; updated_at:string }
export type AccessRequest = { id:string; workbook_id:string; workbook_title?:string; requester_id:string; requester_email?:string; requester_name?:string; requested_role:ShareRole; message?:string; status:'pending'|'approved'|'denied'; decided_by?:string; decided_at?:string; created_at:string }
export type Cell = { sheet_id: string; row: number; column: number; value?: unknown; formula?: string; style?: Record<string, unknown>; spill_source?:string; note?:string; updated_at: string }
export type WorkbookSearchMatch = { sheet_id:string; sheet_name:string; address:string; row:number; column:number; value?:unknown; formula?:string; style?:Record<string,unknown>; spill_source?:string; matched_fields:Array<'value'|'formula'> }
export type WorkbookSearchResult = { workbook_id:string; workbook_version:number; query:string; items:WorkbookSearchMatch[]; next_offset?:number }
export type ReplacePreviewItem = { sheet_id:string; sheet_name:string; address:string; row:number; column:number; field:'value'|'formula'; before:string; after:string }
export type ReplaceResult = { workbook_id:string; workbook_version:number; query:string; replacement:string; preview:boolean; matched_cells:number; planned_cells:number; replaced_cells:number; skipped_cells:number; items:ReplacePreviewItem[]; sheets:Array<{sheet_id:string;sheet_name:string;replaced_cells:number;operation:MutationResult}>; server_version:number }
export type CommentMessage = { id:string; thread_id:string; author_id:string; content:string; mentions:string[]; revision:number; deleted_at?:string; created_at:string; updated_at:string }
export type CommentThread = { id:string; workbook_id:string; sheet_id:string; sheet_name:string; range:string; resolved:boolean; revision:number; created_by:string; resolved_by?:string; resolved_at?:string; created_at:string; updated_at:string; messages:CommentMessage[] }
export type MentionNotification = { id:string; recipient:string; actor_id:string; workbook_id:string; sheet_id:string; sheet_name:string; thread_id:string; message_id:string; range:string; read_at?:string; created_at:string }
export type ChartType = 'bar'|'line'|'area'|'pie'|'scatter'|'histogram'|'stacked_bar'|'stacked_area'|'combo'
export type ChartPosition = { x:number; y:number; width:number; height:number }
export type Chart = { id:string; workbook_id:string; workbook_version:number; sheet_id:string; source_sheet_id?:string; type:ChartType; title:string; source_range:string; first_row_headers:boolean; first_column_labels:boolean; legend_position:'none'|'top'|'right'|'bottom'|'left'; x_axis_title?:string; y_axis_title?:string; secondary_axis?:boolean; position:ChartPosition; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string }
export type ChartPoint = { category:string; value:number|null; x?:number }
export type ChartSeries = { name:string; points:ChartPoint[] }
export type ChartData = { chart:Chart; workbook_version:number; series:ChartSeries[]; warning?:string }
export type PivotGroup = 'none'|'year'|'quarter'|'month'|'day'|'number'|'custom'
// 서버의 internal/workbook/pivot.go 의 pivotAggregations 와 같아야 한다.
// count 는 숫자만, counta 는 비어 있지 않은 것을 센다.
export type PivotAggregation = 'sum'|'average'|'count'|'counta'|'countunique'|'min'|'max'|'median'|'product'|'stdev'|'stdevp'|'var'|'varp'
export type PivotCustomGroup = { name:string; values:string[] }
export type PivotDimension = { column:number; name?:string; group?:PivotGroup; interval?:number; custom_groups?:PivotCustomGroup[] }
export type PivotValueField = { column:number; name?:string; aggregation:PivotAggregation }
export type PivotFilter = { column:number; operator:'equals'|'not_equals'|'contains'|'greater_than'|'greater_or_equal'|'less_than'|'less_or_equal'|'in'|'is_blank'|'not_blank'; value?:string; values?:string[] }
export type PivotCalculatedField = { name:string; formula:string }
export type Pivot = { id:string; workbook_id:string; workbook_version:number; sheet_id:string; source_sheet_id?:string; name:string; source_range:string; first_row_headers:boolean; rows:PivotDimension[]; columns:PivotDimension[]; values:PivotValueField[]; filters?:PivotFilter[]; calculated_fields?:PivotCalculatedField[]; refresh_mode:'auto'|'manual'; source_version:number; last_refreshed_at?:string; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string }
export type PivotResultColumn = { key:string; labels:string[]; value_name:string; value_index?:number; calculated?:boolean }
export type PivotResultRow = { key:string; labels:string[]; values:unknown[]; source_count:number }
export type PivotData = { pivot:Pivot; workbook_version:number; source_version:number; source_headers:string[]; columns:PivotResultColumn[]; rows:PivotResultRow[]; grand_totals:unknown[]; source_row_count:number; generated_at:string; cached:boolean; source_changed_at?:string; stale?:boolean; warning?:string }
export type PivotDrilldownRow = { source_row:number; values:unknown[] }
export type PivotDrilldownResult = { pivot_id:string; headers:string[]; rows:PivotDrilldownRow[]; total:number; next_offset?:number; source_range:string }
export type ValidationViolation = { validation_id:string; row:number; column:number; message:string }
export type CellConflictSnapshot = { value?:unknown; formula?:string; style?:Record<string,unknown>; spill_source?:string }
export type CellConflict = { id:string; workbook_id:string; sheet_id:string; operation_id:string; row:number; column:number; base_version:number; changed_at_version:number; server_version:number; actor_id:string; client_id?:string; conflicting_actor_id?:string; base_cell:CellConflictSnapshot; conflicting_cell:CellConflictSnapshot; submitted_cell:CellConflictSnapshot; applied_cell:CellConflictSnapshot; current_cell:CellConflictSnapshot; status:'open'|'resolved'; resolution?:'keep_current'|'restore_previous'; revision:number; resolved_by?:string; resolution_operation_id?:string; resolution_server_version?:number; resolved_at?:string; created_at:string; updated_at:string }
export type MutationResult = { operation_id: string; workbook_id: string; sheet_id: string; base_version: number; server_version: number; applied_cells: number; recalculated_cells: Array<{sheet_id?:string;row:number;column:number}>; formula_errors: Array<{sheet_id?:string;row:number;column:number;code:string;message:string}>; rebased_cells?:number; dropped_cells?:Array<{row:number;column:number}>; validation_warnings:ValidationViolation[]; duplicate: boolean; conflicts: CellConflict[]; backup_version_id?:string; structural_axis?:'row'|'column'; structural_action?:'insert'|'delete'; structural_index?:number; structural_count?:number; automation_failures?:AutomationFailure[] }
export type AutomationFailure = { automation_id:string; run_id:string; message:string }
export type CellConflictResolutionResult = { conflict:CellConflict; operation:MutationResult }
export type AIConfig = { enabled:boolean; model:string; max_input_cells:number; max_changes:number }
export type AIPromptPreview = { model:string; endpoint?:string; system_prompt:string; user_content:string; cell_count:number; temperature:number; max_tokens:number; estimated_prompt_tokens?:number; context_window?:number }
export type AIUsage = { prompt_tokens?:number; completion_tokens?:number; max_tokens?:number; context_window?:number; attempts?:number; model?:string }
export type AICellSnapshot = { value?:unknown; formula?:string; style?:Record<string,unknown>; spill_source?:string }
export type AIProposedChange = { row:number; column:number; address:string; before:AICellSnapshot; after:AICellSnapshot }
export type AIFinding = { row?:number; column?:number; address?:string; severity:'info'|'warning'|'critical'; title:string; description:string; cell?:AICellSnapshot }
export type AIActionEvent = { id:number; actor_id:string; event_type:string; model?:string; tool_name?:string; payload?:Record<string,unknown>; created_at:string }
export type AgentRisk = 'READ'|'LOW'|'MEDIUM'|'HIGH'|'CRITICAL'
export type AgentState = 'THINKING'|'READING_WORKBOOK'|'PLANNING'|'WAITING_APPROVAL'|'EXECUTING'|'VALIDATING'|'COMPLETED'|'FAILED'|'CANCELLED'
export type AgentPlanStep = { id?:string; position:number; tool:string; description:string; status:string; risk:AgentRisk; arguments?:Record<string,unknown>; result?:Record<string,unknown> }
export type AgentPlan = { id?:string; run_id:string; goal:string; risk:AgentRisk; status:string; steps:AgentPlanStep[]; created_at?:string; updated_at?:string }
export type AgentToolCall = { id?:string; name:string; arguments:Record<string,unknown>; result?:Record<string,unknown>; status:string; risk:AgentRisk; idempotency_key?:string; duration_ms?:number }
export type AgentValidation = { passed:boolean; checks:Array<{name:string;passed:boolean;message:string}>; checked_at?:string }
export type AgentContext = { workbook_id:string; workbook_title:string; workbook_version:number; active_sheet:{id:string;name:string;used_range:string;row_count:number;column_count:number;non_empty_cells:number;formula_cells:number}; selection:string; selected_range:{address:string;cell_count:number;non_empty:number;formula_count:number;blank_count:number;formula_ratio:number}; sheets:Array<{id:string;name:string;used_range:string;row_count:number;column_count:number;non_empty_cells:number;formula_cells:number}>; semantic_map:Array<{column:number;address:string;header?:string;data_type:string;semantic_type?:string;non_empty:number;null_count:number;unique_count:number;formula_count:number;examples?:string[]}>; suggested_prompts:string[] }
export type AgentMessage = { id:string; conversation_id:string; agent_run_id?:string; role:'user'|'assistant'; content:string; created_at:string }
export type AgentConversation = { id:string; workbook_id:string; title:string; latest_run_id?:string; latest_state?:AgentState; message_count:number; run_count:number; created_at:string; updated_at:string }
export type AIAction = { usage?:AIUsage; id:string; workbook_id:string; sheet_id:string; actor_id:string; client_id?:string; mode:'formula'|'explain'|'fix'|'summarize'|'anomaly'|'clean'|'format'|'chart'|'agent'; range:string; request:string; status:'planned'|'completed'|'applying'|'applied'|'undoing'|'undone'|'failed'|'cancelled'; base_version:number; model:string; summary:string; explanation?:string; changes:AIProposedChange[]; findings:AIFinding[]; input_cell_count:number; revision:number; operation_id?:string; operation?:MutationResult; undo_operation_id?:string; undo_operation?:MutationResult; error_message?:string; approved_at?:string; undone_at?:string; created_at:string; updated_at:string; events?:AIActionEvent[]; duplicate?:boolean; conversation_id?:string; risk:AgentRisk; plan:AgentPlanStep[]; tool_calls:AgentToolCall[]; validation:AgentValidation }
export type AIExecutionResult = { action:AIAction; operation:MutationResult; changes?:Array<{row:number;column:number;formula?:string;value?:unknown;style?:Record<string,unknown>}> }
export type AgentRun = { id:string; conversation_id:string; change_set_id?:string; workbook_id:string; sheet_id:string; selection:string; intent:string; state:AgentState; goal:string; risk:AgentRisk; context:AgentContext; plan:AgentPlan; action:AIAction; messages:AgentMessage[]; suggested_follow_ups?:string[]; validation:AgentValidation; started_at:string; completed_at?:string; updated_at:string }
export type AgentExecutionResult = { run:AgentRun; operation?:MutationResult; changes?:Array<{row:number;column:number;formula?:string;value?:unknown;style?:Record<string,unknown>}> }
export type AutomationTrigger = { type:'manual'|'cell_change'|'schedule'|'webhook'; sheet_id?:string; range?:string; cron?:string; timezone?:string }
export type AutomationAction = { type:'set_value'|'set_formula'|'clear'; sheet_id:string; range:string; value?:unknown; formula?:string }
export type Automation = { id:string; workbook_id:string; name:string; enabled:boolean; trigger:AutomationTrigger; action:AutomationAction; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string; next_run_at?:string; last_failure?:AutomationRunFailure; duplicate?:boolean }
export type AutomationRunFailure = { run_id:string; trigger_type:AutomationRun['trigger_type']; message:string; at:string }
export type AutomationOverview = { items:Automation[]; execution_enabled:boolean }
export type AutomationCellSnapshot = { value?:unknown; formula?:string; style?:Record<string,unknown>; spill_source?:string }
export type AutomationPreviewChange = { row:number; column:number; address:string; before:AutomationCellSnapshot; after:AutomationCellSnapshot }
export type AutomationPreview = { automation_id:string; automation_name:string; workbook_id:string; automation_revision:number; base_version:number; action:AutomationAction; changes:AutomationPreviewChange[] }
export type AutomationRun = { id:string; automation_id:string; workbook_id:string; actor_id:string; trigger_type:'manual'|'cell_change'|'schedule'|'webhook'; trigger_operation_id?:string; scheduled_for?:string; trigger_key_id?:string; payload_digest?:string; payload_bytes?:number; status:'running'|'succeeded'|'skipped'|'failed'|'undoing'|'undone'; base_version:number; action:AutomationAction; operation_id?:string; operation?:MutationResult; undo_operation_id?:string; undo_operation?:MutationResult; error_message?:string; started_at:string; completed_at?:string; updated_at:string; duplicate?:boolean }
export type AutomationExecutionResult = { run:AutomationRun; operation:MutationResult; changes?:Array<{row:number;column:number;formula?:string;value?:unknown;style?:Record<string,unknown>}> }
export type WorkbookVersion = { id:string; workbook_id:string; workbook_version:number; name:string; actor_id:string; created_at:string }
export type SystemSetting = { key: string; value?: unknown; value_type: 'string'|'number'|'boolean'|'string_list'|'object'; description?: string; secret: boolean; configured?: boolean; updated_at: string; updated_by: string }
export type SettingVersion = { revision:number; change_summary:string; actor_id:string; created_at:string }
export type LogEntry = { id:number; logged_at:string; level:string; message:string; attributes:Record<string,unknown>; trace_id?:string }
export type ApiKey = { id:string; user_id:string; name:string; prefix:string; scopes:string[]; expires_at?:string; last_used_at?:string; revoked_at?:string; created_at:string; updated_at:string }
export type CreatedApiKey = ApiKey & { secret:string }
export type FilterOperator = 'values'|'equals'|'not_equals'|'contains'|'not_contains'|'starts_with'|'ends_with'|'greater_than'|'greater_or_equal'|'less_than'|'less_or_equal'|'is_blank'|'is_not_blank'|'background_color'|'text_color'
export type FilterCriterion = { column:number; operator:FilterOperator; value?:unknown; values?:unknown[]; color?:string; case_sensitive?:boolean }
export type FilterView = { id:string; sheet_id:string; actor_id:string; name:string; range:string; header_rows:number; criteria:FilterCriterion[]; active:boolean; created_at:string; updated_at:string }
export type FilterResult = { filter_view_id:string; range:string; hidden_rows:number[]; visible_count:number; hidden_count:number; total_count:number }
export type ProtectedRange = { id:string; sheet_id:string; range:string; scope?:'range'|'sheet'; exceptions?:string[]; description?:string; editors:string[]; warning_only:boolean; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string }
export type ValidationRuleType = 'list'|'list_range'|'checkbox'|'number'|'date'|'custom_formula'
export type ValidationOperator = 'in_list'|'between'|'not_between'|'equal'|'not_equal'|'greater_than'|'greater_or_equal'|'less_than'|'less_or_equal'|'custom'
export type ValidationOption = { value:unknown; label?:string; color?:string }
export type DataValidation = { id:string; workbook_id:string; workbook_version:number; sheet_id:string; range:string; rule_type:ValidationRuleType; operator:ValidationOperator; options?:ValidationOption[]; source_range?:string; source_options?:ValidationOption[]; value?:unknown; value2?:unknown; formula?:string; allow_blank:boolean; reject_input:boolean; show_dropdown:boolean; display_style:'chip'|'arrow'|'plain'; help_text?:string; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string }
export type ValidationEvaluation = { validation_id:string; range:string; checked_cells:number; valid_cells:number; invalid_cells:ValidationViolation[]; truncated:boolean }
export type ConditionalFormatRuleType = 'value'|'custom_formula'|'duplicate'|'rank'|'color_scale'|'data_bar'|'icon_set'
export type ConditionalIconStyle = '3Arrows'|'3TrafficLights1'|'3Symbols'|'4Arrows'|'5Arrows'|'5Quarters'
export type ConditionalFormatOperator = 'equals'|'not_equals'|'greater_than'|'greater_or_equal'|'less_than'|'less_or_equal'|'between'|'not_between'|'contains'|'not_contains'|'is_blank'|'not_blank'|'duplicate'|'unique'|'top'|'bottom'|'top_percent'|'bottom_percent'
export type ConditionalFormat = { id:string; workbook_id:string; workbook_version:number; sheet_id:string; name:string; range:string; rule_type:ConditionalFormatRuleType; operator?:ConditionalFormatOperator; formula?:string; value?:unknown; value2?:unknown; style?:Record<string,unknown>; min_color?:string; mid_color?:string; max_color?:string; bar_color?:string; icon_style?:ConditionalIconStyle; icon_reverse?:boolean; priority:number; stop_if_true:boolean; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string }
export type ConditionalDataBar = { color:string; ratio:number }
export type ConditionalIcon = { style:ConditionalIconStyle; index:number; count:number }
export type ConditionalFormatCell = { row:number; column:number; style?:Record<string,unknown>; data_bar?:ConditionalDataBar; icon?:ConditionalIcon; matched_rule_ids:string[] }
export type ConditionalFormatEvaluation = { workbook_version:number; sheet_id:string; range:string; items:ConditionalFormatCell[] }
export type NamedRange = { id:string; workbook_id:string; workbook_version:number; sheet_id:string; name:string; range:string; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string }
export type AIHistoryItem = { id:string; workbook_id:string; workbook_title:string; actor_id:string; mode:AIAction['mode']; range:string; request:string; status:AIAction['status']; model:string; summary?:string; error_message?:string; change_count:number; finding_count:number; input_cell_count:number; prompt_tokens:number; completion_tokens:number; attempts:number; created_at:string; updated_at:string }
export type AIHistorySummary = { total:number; by_status:Record<string,number>; by_mode:Record<string,number>; prompt_tokens:number; completion_tokens:number; applied_cells:number; top_actors:Array<{actor_id:string;count:number;tokens:number}>; oldest_at?:string; newest_at?:string; retention_days:number }
export type AIHistoryPage = { items:AIHistoryItem[]; summary:AIHistorySummary; next_offset?:number }
export type MailDelivery = { id:string; event:string; recipient:string; subject:string; workbook_id?:string; actor_id?:string; status:'queued'|'sent'|'failed'|'skipped'; attempts:number; error_message?:string; created_at:string; updated_at:string }
export type MailDeliveryPage = { items:MailDelivery[]; summary:{ total:number; status:Record<string,number> } }
