export type BuildInfo = { product: string; version: string; commit: string; build_time: string; go_version: string }
export type AuthConfig = { oidc_enabled:boolean; bootstrap_login_enabled:boolean; issuer_url:string; client_id:string; client_secret_configured:boolean }
export type User = { id: string; email?: string; display_name: string; roles: string[]; expires_at: string }
export type Session = { authenticated: boolean; user?: User; admin?: boolean }
export type Sheet = { id: string; workbook_id: string; name: string; position: number; color?: string; hidden: boolean; created_at: string }
export type Workbook = { id: string; workspace_id: string; title: string; owner_id: string; favorite: boolean; version: number; created_at: string; updated_at: string; sheets: Sheet[] }
export type Cell = { sheet_id: string; row: number; column: number; value?: unknown; formula?: string; style?: Record<string, unknown>; spill_source?:string; updated_at: string }
export type ValidationViolation = { validation_id:string; row:number; column:number; message:string }
export type MutationResult = { operation_id: string; workbook_id: string; sheet_id: string; base_version: number; server_version: number; applied_cells: number; recalculated_cells: Array<{row:number;column:number}>; formula_errors: Array<{row:number;column:number;code:string;message:string}>; validation_warnings:ValidationViolation[]; duplicate: boolean; conflicts: Array<{row:number;column:number;changed_at_version:number;previous_value?:unknown;submitted_value?:unknown}> }
export type WorkbookVersion = { id:string; workbook_id:string; workbook_version:number; name:string; actor_id:string; created_at:string }
export type SystemSetting = { key: string; value?: unknown; value_type: 'string'|'number'|'boolean'|'string_list'|'object'; description?: string; secret: boolean; configured?: boolean; updated_at: string; updated_by: string }
export type SettingVersion = { revision:number; change_summary:string; actor_id:string; created_at:string }
export type LogEntry = { id:number; logged_at:string; level:string; message:string; attributes:Record<string,unknown>; trace_id?:string }
export type ApiKey = { id:string; user_id:string; name:string; prefix:string; scopes:string[]; expires_at?:string; last_used_at?:string; revoked_at?:string; created_at:string }
export type CreatedApiKey = ApiKey & { secret:string }
export type FilterOperator = 'values'|'equals'|'not_equals'|'contains'|'not_contains'|'starts_with'|'ends_with'|'greater_than'|'greater_or_equal'|'less_than'|'less_or_equal'|'is_blank'|'is_not_blank'|'background_color'|'text_color'
export type FilterCriterion = { column:number; operator:FilterOperator; value?:unknown; values?:unknown[]; color?:string; case_sensitive?:boolean }
export type FilterView = { id:string; sheet_id:string; actor_id:string; name:string; range:string; header_rows:number; criteria:FilterCriterion[]; active:boolean; created_at:string; updated_at:string }
export type FilterResult = { filter_view_id:string; range:string; hidden_rows:number[]; visible_count:number; hidden_count:number; total_count:number }
export type ValidationRuleType = 'list'|'number'|'date'|'custom_formula'
export type ValidationOperator = 'in_list'|'between'|'not_between'|'equal'|'not_equal'|'greater_than'|'greater_or_equal'|'less_than'|'less_or_equal'|'custom'
export type ValidationOption = { value:unknown; label?:string; color?:string }
export type DataValidation = { id:string; workbook_id:string; workbook_version:number; sheet_id:string; range:string; rule_type:ValidationRuleType; operator:ValidationOperator; options?:ValidationOption[]; value?:unknown; value2?:unknown; formula?:string; allow_blank:boolean; reject_input:boolean; show_dropdown:boolean; display_style:'chip'|'arrow'|'plain'; help_text?:string; revision:number; created_by:string; updated_by:string; created_at:string; updated_at:string }
export type ValidationEvaluation = { validation_id:string; range:string; checked_cells:number; valid_cells:number; invalid_cells:ValidationViolation[]; truncated:boolean }
