import { BarChart3,Trash2 } from 'lucide-react'
import { useEffect,useState } from 'react'
import type { Chart,ChartPosition,ChartType,Sheet } from '../types'
import './ChartDialog.css'

type Draft={type:ChartType;title:string;sourceSheetId:string;sourceRange:string;firstRowHeaders:boolean;firstColumnLabels:boolean;legendPosition:Chart['legend_position'];xAxisTitle:string;yAxisTitle:string;position:ChartPosition}
const chartTypes:Array<[ChartType,string]>=[['bar','막대'],['line','선'],['area','영역'],['pie','원형'],['scatter','분산'],['histogram','히스토그램']]
const defaultPosition:ChartPosition={x:24,y:24,width:560,height:320}
const validCell=(value:string)=>/^[A-Z]+[1-9]\d*$/i.test(value.trim().replaceAll('$',''))
const validRange=(value:string)=>{const parts=value.split(':');return parts.length>0&&parts.length<=2&&parts.every(validCell)}
const draftFor=(chart:Chart|undefined,activeSheetId:string,selectionRange:string):Draft=>chart?{type:chart.type,title:chart.title,sourceSheetId:chart.source_sheet_id??activeSheetId,sourceRange:chart.source_range,firstRowHeaders:chart.first_row_headers,firstColumnLabels:chart.first_column_labels,legendPosition:chart.legend_position,xAxisTitle:chart.x_axis_title??'',yAxisTitle:chart.y_axis_title??'',position:chart.position}:{type:'bar',title:'',sourceSheetId:activeSheetId,sourceRange:selectionRange,firstRowHeaders:true,firstColumnLabels:true,legendPosition:'right',xAxisTitle:'',yAxisTitle:'',position:defaultPosition}

export function ChartDialog({chart,activeSheetId,selectionRange,sheets,onClose,onCreate,onUpdate,onDelete}:{
  chart?:Chart;activeSheetId:string;selectionRange:string;sheets:Sheet[];onClose:()=>void
  onCreate:(input:Record<string,unknown>)=>Promise<Chart>;onUpdate:(chart:Chart,input:Record<string,unknown>)=>Promise<Chart>;onDelete:(chart:Chart)=>Promise<void>
}){
  const [draft,setDraft]=useState(()=>draftFor(chart,activeSheetId,selectionRange)),[saving,setSaving]=useState(false)
  useEffect(()=>setDraft(draftFor(chart,activeSheetId,selectionRange)),[chart,activeSheetId,selectionRange])
  const patch=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}))
  const save=async()=>{if(!validRange(draft.sourceRange))return alert('올바른 A1 원본 범위를 입력하세요.');setSaving(true);try{const input={sheet_id:chart?.sheet_id??activeSheetId,source_sheet_id:draft.sourceSheetId,type:draft.type,title:draft.title,source_range:draft.sourceRange.toUpperCase(),first_row_headers:draft.firstRowHeaders,first_column_labels:draft.firstColumnLabels,legend_position:draft.legendPosition,x_axis_title:draft.xAxisTitle,y_axis_title:draft.yAxisTitle,position:draft.position};if(chart)await onUpdate(chart,{...input,expected_revision:chart.revision});else await onCreate(input);onClose()}catch(error){alert(error instanceof Error?error.message:'차트를 저장하지 못했습니다.')}finally{setSaving(false)}}
  const remove=async()=>{if(!chart||!confirm('이 차트를 삭제할까요?'))return;setSaving(true);try{await onDelete(chart);onClose()}catch(error){alert(error instanceof Error?error.message:'차트를 삭제하지 못했습니다.')}finally{setSaving(false)}}
  return <div className="modal-backdrop"><div className="modal chart-dialog" role="dialog" aria-modal="true" aria-label={chart?'차트 편집':'차트 만들기'}><header><div><BarChart3/><div><h2>{chart?'차트 편집':'차트 만들기'}</h2><p>최신 서버 셀 값을 사용하며 원본이 바뀌면 자동 갱신됩니다.</p></div></div><button aria-label="차트 대화상자 닫기" onClick={onClose}>×</button></header><section><div className="chart-fields two"><label>차트 유형<select aria-label="차트 유형" value={draft.type} onChange={event=>patch('type',event.target.value as ChartType)}>{chartTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>차트 제목<input aria-label="차트 제목" maxLength={200} value={draft.title} onChange={event=>patch('title',event.target.value)} placeholder="월별 매출"/></label></div><div className="chart-fields two"><label>원본 시트<select aria-label="차트 원본 시트" value={draft.sourceSheetId} onChange={event=>patch('sourceSheetId',event.target.value)}>{sheets.map(sheet=><option value={sheet.id} key={sheet.id}>{sheet.name}</option>)}</select></label><label>원본 범위<input aria-label="차트 원본 범위" value={draft.sourceRange} onChange={event=>patch('sourceRange',event.target.value)} placeholder="A1:C20"/></label></div><div className="chart-checks"><label><input type="checkbox" checked={draft.firstRowHeaders} onChange={event=>patch('firstRowHeaders',event.target.checked)}/> 첫 행을 계열 이름으로 사용</label><label><input type="checkbox" checked={draft.firstColumnLabels} onChange={event=>patch('firstColumnLabels',event.target.checked)}/> 첫 열을 항목 이름으로 사용</label></div><div className="chart-fields three"><label>범례<select value={draft.legendPosition} onChange={event=>patch('legendPosition',event.target.value as Chart['legend_position'])}><option value="right">오른쪽</option><option value="top">위</option><option value="bottom">아래</option><option value="left">왼쪽</option><option value="none">숨김</option></select></label><label>X축 제목<input maxLength={100} value={draft.xAxisTitle} onChange={event=>patch('xAxisTitle',event.target.value)}/></label><label>Y축 제목<input maxLength={100} value={draft.yAxisTitle} onChange={event=>patch('yAxisTitle',event.target.value)}/></label></div><div className="chart-size-fields"><label>너비<input type="number" min={240} max={1600} value={draft.position.width} onChange={event=>patch('position',{...draft.position,width:Number(event.target.value)})}/></label><label>높이<input type="number" min={160} max={1200} value={draft.position.height} onChange={event=>patch('position',{...draft.position,height:Number(event.target.value)})}/></label></div></section><div className="modal-actions chart-actions">{chart&&<button className="danger" disabled={saving} onClick={remove}><Trash2/> 삭제</button>}<span/><button className="secondary" onClick={onClose}>취소</button><button className="primary" disabled={saving||!validRange(draft.sourceRange)} onClick={save}>{saving?'저장 중…':'차트 저장'}</button></div></div></div>
}
