import { Palette,Plus,Trash2 } from 'lucide-react'
import { useState } from 'react'
import { address } from '../lib/api'
import { parseFilterInput,parseFilterRange } from '../lib/filter'
import type { MergeRange } from '../lib/merge'
import type { ConditionalFormat,ConditionalFormatOperator,ConditionalFormatRuleType } from '../types'
import './ConditionalFormatDialog.css'

type Draft={name:string;range:string;ruleType:ConditionalFormatRuleType;operator:ConditionalFormatOperator;value:string;value2:string;background:string;color:string;bold:boolean;italic:boolean;minColor:string;midColor:string;maxColor:string;useMidColor:boolean;barColor:string;priority:number;stopIfTrue:boolean}

const types:Array<[ConditionalFormatRuleType,string]>=[['value','값 조건'],['duplicate','중복·고유 값'],['color_scale','색상 범위'],['data_bar','데이터 막대']]
const valueOperators:Array<[ConditionalFormatOperator,string]>=[['greater_than','보다 큼'],['greater_or_equal','이상'],['less_than','보다 작음'],['less_or_equal','이하'],['equals','같음'],['not_equals','같지 않음'],['between','사이'],['not_between','사이 아님'],['contains','텍스트 포함'],['not_contains','텍스트 미포함'],['is_blank','비어 있음'],['not_blank','비어 있지 않음']]
const needsValue=(operator:ConditionalFormatOperator)=>operator!=='is_blank'&&operator!=='not_blank'
const needsSecond=(operator:ConditionalFormatOperator)=>operator==='between'||operator==='not_between'
const ruleTypeLabel=(type:ConditionalFormatRuleType)=>types.find(([value])=>value===type)?.[1]??type
const draftValue=(value:unknown)=>value==null?'':String(value)
const defaultDraft=(range:MergeRange):Draft=>({name:'',range:`${address(range.startRow,range.startColumn)}:${address(range.endRow,range.endColumn)}`,ruleType:'value',operator:'greater_than',value:'',value2:'',background:'#fee2e2',color:'#991b1b',bold:false,italic:false,minColor:'#dcfce7',midColor:'#fef3c7',maxColor:'#ef4444',useMidColor:false,barColor:'#38a3a5',priority:1,stopIfTrue:false})
const draftFromRule=(rule:ConditionalFormat):Draft=>({name:rule.name,range:rule.range,ruleType:rule.rule_type,operator:rule.operator??(rule.rule_type==='duplicate'?'duplicate':'greater_than'),value:draftValue(rule.value),value2:draftValue(rule.value2),background:typeof rule.style?.background==='string'?rule.style.background:'#fee2e2',color:typeof rule.style?.color==='string'?rule.style.color:'#991b1b',bold:rule.style?.bold===true,italic:rule.style?.italic===true,minColor:rule.min_color??'#dcfce7',midColor:rule.mid_color??'#fef3c7',maxColor:rule.max_color??'#ef4444',useMidColor:Boolean(rule.mid_color),barColor:rule.bar_color??'#38a3a5',priority:rule.priority,stopIfTrue:rule.stop_if_true})

export function ConditionalFormatDialog({range,rules,onClose,onCreate,onUpdate,onDelete}:{
  range:MergeRange;rules:ConditionalFormat[];onClose:()=>void
  onCreate:(input:Record<string,unknown>)=>Promise<ConditionalFormat>;onUpdate:(id:string,input:Record<string,unknown>)=>Promise<ConditionalFormat>;onDelete:(rule:ConditionalFormat)=>Promise<void>
}){
  const [selectedId,setSelectedId]=useState<string>(),[draft,setDraft]=useState<Draft>(()=>defaultDraft(range)),[saving,setSaving]=useState(false)
  const selected=rules.find(rule=>rule.id===selectedId)
  const choose=(rule?:ConditionalFormat)=>{setSelectedId(rule?.id);setDraft(rule?draftFromRule(rule):defaultDraft(range))}
  const changeType=(ruleType:ConditionalFormatRuleType)=>setDraft(current=>({...current,ruleType,operator:ruleType==='duplicate'?'duplicate':ruleType==='value'?'greater_than':current.operator,stopIfTrue:ruleType==='value'||ruleType==='duplicate'?current.stopIfTrue:false}))
  const save=async()=>{
    if(!parseFilterRange(draft.range))return alert('올바른 A1 범위를 입력하세요.')
    if(draft.ruleType==='value'&&needsValue(draft.operator)&&draft.value.trim()==='')return alert('조건 기준값을 입력하세요.')
    if(draft.ruleType==='value'&&needsSecond(draft.operator)&&draft.value2.trim()==='')return alert('두 번째 기준값을 입력하세요.')
    if(draft.ruleType==='value'&&needsSecond(draft.operator)&&(!Number.isFinite(Number(draft.value))||!Number.isFinite(Number(draft.value2))))return alert('사이 조건의 기준값은 숫자로 입력하세요.')
    const input:Record<string,unknown>={name:draft.name.trim(),range:draft.range.toUpperCase(),rule_type:draft.ruleType,priority:draft.priority,stop_if_true:draft.ruleType==='value'||draft.ruleType==='duplicate'?draft.stopIfTrue:false}
    if(draft.ruleType==='value'){
      input.operator=draft.operator
      if(needsValue(draft.operator))input.value=needsSecond(draft.operator)?Number(draft.value):parseFilterInput(draft.value)
      if(needsSecond(draft.operator))input.value2=Number(draft.value2)
      input.style={background:draft.background,color:draft.color,bold:draft.bold,italic:draft.italic}
    }else if(draft.ruleType==='duplicate'){
      input.operator=draft.operator
      input.style={background:draft.background,color:draft.color,bold:draft.bold,italic:draft.italic}
    }else if(draft.ruleType==='color_scale'){
      input.min_color=draft.minColor;input.mid_color=draft.useMidColor?draft.midColor:'';input.max_color=draft.maxColor
    }else input.bar_color=draft.barColor
    setSaving(true)
    try{const saved=selected?await onUpdate(selected.id,{...input,expected_revision:selected.revision}):await onCreate(input);choose(saved)}catch(error){alert(error instanceof Error?error.message:'조건부 서식 규칙을 저장하지 못했습니다.')}finally{setSaving(false)}
  }
  const remove=async(rule:ConditionalFormat)=>{if(!confirm(`${rule.range} 조건부 서식을 삭제할까요?`))return;setSaving(true);try{await onDelete(rule);choose()}catch(error){alert(error instanceof Error?error.message:'조건부 서식을 삭제하지 못했습니다.')}finally{setSaving(false)}}
  return <div className="modal-backdrop"><div className="modal validation-modal conditional-format-modal" role="dialog" aria-modal="true" aria-label="조건부 서식"><header><div><Palette/><div><h2>조건부 서식</h2><p>값 비교, 중복, 색상 범위와 데이터 막대를 서버 권위 규칙으로 표시합니다.</p></div></div><button aria-label="조건부 서식 닫기" onClick={onClose}>×</button></header><div className="validation-layout"><aside><button className={!selected?'active':''} onClick={()=>choose()}><Plus/> 새 서식 규칙</button>{rules.map(rule=><button key={rule.id} className={selected?.id===rule.id?'active':''} onClick={()=>choose(rule)}><span>{rule.name||rule.range}</span><em>{rule.range} · {ruleTypeLabel(rule.rule_type)} · 우선순위 {rule.priority}</em></button>)}</aside><section><div className="validation-fields three"><label>규칙 이름<input aria-label="조건부 서식 이름" maxLength={200} value={draft.name} onChange={event=>setDraft(current=>({...current,name:event.target.value}))} placeholder="예: 목표 초과"/></label><label>적용 범위<input aria-label="조건부 서식 범위" value={draft.range} onChange={event=>setDraft(current=>({...current,range:event.target.value}))}/></label><label>규칙 유형<select aria-label="조건부 서식 유형" value={draft.ruleType} onChange={event=>changeType(event.target.value as ConditionalFormatRuleType)}>{types.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
    {draft.ruleType==='value'&&<div className="validation-fields three"><label>조건<select aria-label="조건부 서식 조건" value={draft.operator} onChange={event=>setDraft(current=>({...current,operator:event.target.value as ConditionalFormatOperator}))}>{valueOperators.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{needsValue(draft.operator)&&<label>기준값<input aria-label="조건부 서식 기준값" value={draft.value} onChange={event=>setDraft(current=>({...current,value:event.target.value}))}/></label>}{needsSecond(draft.operator)&&<label>두 번째 기준값<input aria-label="조건부 서식 두 번째 기준값" type="number" value={draft.value2} onChange={event=>setDraft(current=>({...current,value2:event.target.value}))}/></label>}</div>}
    {draft.ruleType==='duplicate'&&<div className="validation-fields"><label>표시할 값<select aria-label="중복 값 조건" value={draft.operator} onChange={event=>setDraft(current=>({...current,operator:event.target.value as ConditionalFormatOperator}))}><option value="duplicate">중복 값</option><option value="unique">고유 값</option></select></label></div>}
    {(draft.ruleType==='value'||draft.ruleType==='duplicate')&&<fieldset className="conditional-style"><legend>적용할 셀 서식</legend><label>배경색<input aria-label="조건부 배경색" type="color" value={draft.background} onChange={event=>setDraft(current=>({...current,background:event.target.value}))}/></label><label>글자색<input aria-label="조건부 글자색" type="color" value={draft.color} onChange={event=>setDraft(current=>({...current,color:event.target.value}))}/></label><label className="conditional-check"><input aria-label="조건부 굵게" type="checkbox" checked={draft.bold} onChange={event=>setDraft(current=>({...current,bold:event.target.checked}))}/> 굵게</label><label className="conditional-check"><input aria-label="조건부 기울임" type="checkbox" checked={draft.italic} onChange={event=>setDraft(current=>({...current,italic:event.target.checked}))}/> 기울임</label><span className="conditional-preview" style={{background:draft.background,color:draft.color,fontWeight:draft.bold?700:400,fontStyle:draft.italic?'italic':'normal'}}>미리보기 Aa 123</span></fieldset>}
    {draft.ruleType==='color_scale'&&<fieldset className="conditional-style color-scale"><legend>색상 범위</legend><label>최솟값 색상<input aria-label="최솟값 색상" type="color" value={draft.minColor} onChange={event=>setDraft(current=>({...current,minColor:event.target.value}))}/></label><label>최댓값 색상<input aria-label="최댓값 색상" type="color" value={draft.maxColor} onChange={event=>setDraft(current=>({...current,maxColor:event.target.value}))}/></label><label className="conditional-check"><input aria-label="중간 색상 사용" type="checkbox" checked={draft.useMidColor} onChange={event=>setDraft(current=>({...current,useMidColor:event.target.checked}))}/> 중간 색상 사용</label>{draft.useMidColor&&<label>중간값 색상<input aria-label="중간값 색상" type="color" value={draft.midColor} onChange={event=>setDraft(current=>({...current,midColor:event.target.value}))}/></label>}<span className="conditional-gradient" style={{background:`linear-gradient(90deg,${draft.minColor}${draft.useMidColor?`,${draft.midColor}`:''},${draft.maxColor})`}}/></fieldset>}
    {draft.ruleType==='data_bar'&&<fieldset className="conditional-style data-bar-style"><legend>데이터 막대</legend><label>막대 색상<input aria-label="데이터 막대 색상" type="color" value={draft.barColor} onChange={event=>setDraft(current=>({...current,barColor:event.target.value}))}/></label><span className="conditional-bar-preview"><i style={{background:draft.barColor}}/></span></fieldset>}
    <div className="validation-fields conditional-options"><label>우선순위<input aria-label="조건부 서식 우선순위" type="number" min={1} max={1000} value={draft.priority} onChange={event=>setDraft(current=>({...current,priority:Number(event.target.value)}))}/></label>{(draft.ruleType==='value'||draft.ruleType==='duplicate')&&<label className="conditional-check stop"><input aria-label="조건이 참이면 중지" type="checkbox" checked={draft.stopIfTrue} onChange={event=>setDraft(current=>({...current,stopIfTrue:event.target.checked}))}/> 조건이 참이면 낮은 우선순위 규칙 중지</label>}</div>
    <div className="modal-actions validation-actions">{selected&&<button className="danger" disabled={saving} onClick={()=>remove(selected)}><Trash2/> 삭제</button>}<span/><button className="secondary" onClick={onClose}>닫기</button><button className="primary" disabled={saving||!parseFilterRange(draft.range)||draft.priority<1||draft.priority>1000} onClick={save}>{saving?'저장 중…':'규칙 저장'}</button></div></section></div></div></div>
}
