import {useState} from 'react'
import { useDialog } from '../lib/useDialog'

export type BorderFormatCommand={preset:'all'|'outer'|'inner'|'horizontal'|'vertical'|'top'|'right'|'bottom'|'left'|'none';style?:'none'|'thin'|'medium'|'thick'|'dashed'|'dotted'|'double';color?:string}

const knownStyleKeys=['bold','italic','underline','strike','wrap','color','background','font_family','font_size','horizontal_align','vertical_align','number_format','text_mode','text_rotation','borders']
const numberFormatPresets=new Set(['#,##0','#,##0.00','₩#,##0','$#,##0.00','0%','0.00%','yyyy-mm-dd','hh:mm:ss','yyyy-mm-dd hh:mm'])

export function FormatDialog({style,onClose,onApply}:{style?:Record<string,unknown>;onClose:()=>void;onApply:(patch:Record<string,unknown>,border?:BorderFormatCommand)=>Promise<void>}){
  const initialNumberFormat=typeof style?.number_format==='string'?style.number_format:''
  const [numberFormat,setNumberFormat]=useState(initialNumberFormat?(numberFormatPresets.has(initialNumberFormat)?initialNumberFormat:'custom'):'general')
  const [customFormat,setCustomFormat]=useState(initialNumberFormat||'#,##0.00')
  const [horizontal,setHorizontal]=useState(typeof style?.horizontal_align==='string'?style.horizontal_align:'left'),[vertical,setVertical]=useState(typeof style?.vertical_align==='string'?style.vertical_align:'middle')
  const [textMode,setTextMode]=useState(typeof style?.text_mode==='string'?style.text_mode:style?.wrap===true?'wrap':'overflow'),[rotation,setRotation]=useState(typeof style?.text_rotation==='number'?style.text_rotation:0)
  const [borderPreset,setBorderPreset]=useState<BorderFormatCommand['preset']>('outer'),[borderStyle,setBorderStyle]=useState<NonNullable<BorderFormatCommand['style']>>('thin'),[borderColor,setBorderColor]=useState('#1c2733'),[includeBorder,setIncludeBorder]=useState(false),[saving,setSaving]=useState(false)
  const resolvedFormat=numberFormat==='custom'?customFormat:numberFormat
  const submit=async()=>{setSaving(true);try{const patch:Record<string,unknown>={number_format:resolvedFormat==='general'?null:resolvedFormat,horizontal_align:horizontal,vertical_align:vertical,text_mode:textMode,text_rotation:rotation,wrap:null};const border=includeBorder?(borderPreset==='none'?{preset:'none'}:{preset:borderPreset,style:borderStyle,color:borderColor}) as BorderFormatCommand:undefined;await onApply(patch,border);onClose()}finally{setSaving(false)}}
  const clear=async()=>{setSaving(true);try{await onApply(Object.fromEntries(knownStyleKeys.map(key=>[key,null])));onClose()}finally{setSaving(false)}}
  const dialog=useDialog<HTMLElement>(onClose)
  return <div className="modal-backdrop"><div className="modal format-modal" role="dialog" ref={dialog as React.RefObject<any>} aria-modal="true" aria-label="셀 서식">
    <h2>셀 서식</h2><p>선택 범위의 표시 형식, 정렬, 텍스트 배치와 테두리를 한 번에 저장합니다.</p>
    <div className="format-grid"><label>표시 형식<select value={numberFormat} onChange={event=>setNumberFormat(event.target.value)}><option value="general">일반</option><option value="#,##0">숫자</option><option value="#,##0.00">숫자 (소수 2자리)</option><option value="₩#,##0">원화</option><option value="$#,##0.00">달러</option><option value="0%">백분율</option><option value="0.00%">백분율 (소수 2자리)</option><option value="yyyy-mm-dd">날짜</option><option value="hh:mm:ss">시간</option><option value="yyyy-mm-dd hh:mm">날짜와 시간</option><option value="custom">사용자 지정</option></select></label>{numberFormat==='custom'&&<label>사용자 지정 형식<input value={customFormat} maxLength={100} onChange={event=>setCustomFormat(event.target.value)}/></label>}<label>가로 정렬<select value={horizontal} onChange={event=>setHorizontal(event.target.value)}><option value="left">왼쪽</option><option value="center">가운데</option><option value="right">오른쪽</option></select></label><label>세로 정렬<select value={vertical} onChange={event=>setVertical(event.target.value)}><option value="top">위</option><option value="middle">가운데</option><option value="bottom">아래</option></select></label><label>텍스트 배치<select value={textMode} onChange={event=>setTextMode(event.target.value)}><option value="overflow">넘침</option><option value="clip">자르기</option><option value="wrap">자동 줄 바꿈</option></select></label><label>텍스트 회전<input type="number" min={-90} max={90} value={rotation} onChange={event=>setRotation(Number(event.target.value))}/></label></div>
    <section className="format-border"><label className="format-check"><input type="checkbox" checked={includeBorder} onChange={event=>setIncludeBorder(event.target.checked)}/>테두리도 적용</label><div><label>범위<select disabled={!includeBorder} value={borderPreset} onChange={event=>setBorderPreset(event.target.value as BorderFormatCommand['preset'])}><option value="all">모든 테두리</option><option value="outer">바깥쪽</option><option value="inner">안쪽</option><option value="horizontal">안쪽 가로</option><option value="vertical">안쪽 세로</option><option value="top">위쪽</option><option value="right">오른쪽</option><option value="bottom">아래쪽</option><option value="left">왼쪽</option><option value="none">테두리 지우기</option></select></label><label>선<select disabled={!includeBorder||borderPreset==='none'} value={borderStyle} onChange={event=>setBorderStyle(event.target.value as NonNullable<BorderFormatCommand['style']>)}><option value="thin">가는 실선</option><option value="medium">중간 실선</option><option value="thick">굵은 실선</option><option value="dashed">파선</option><option value="dotted">점선</option><option value="double">이중선</option></select></label><label>색<input disabled={!includeBorder||borderPreset==='none'} type="color" value={borderColor} onChange={event=>setBorderColor(event.target.value)}/></label></div></section>
    <div className="structure-note">범위 서식은 값과 수식을 변경하지 않으며 버전 이력과 실행 취소에 포함됩니다.</div><div className="modal-actions"><button className="danger secondary" disabled={saving} onClick={()=>void clear()}>서식 지우기</button><span/><button className="secondary" disabled={saving} onClick={onClose}>취소</button><button className="primary" disabled={saving||numberFormat==='custom'&&!customFormat.trim()||rotation<-90||rotation>90} onClick={()=>void submit()}>적용</button></div>
  </div></div>
}
