import { useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, RefreshCw, Rows3, Table2 } from 'lucide-react'
import { useState } from 'react'
import { api } from '../lib/api'
import type { Pivot, PivotData, PivotDrilldownResult } from '../types'
import './PivotResultDialog.css'
import { useDialog } from '../lib/useDialog'

const display=(value:unknown)=>value==null?'—':typeof value==='number'?new Intl.NumberFormat('ko-KR',{maximumFractionDigits:6}).format(value):String(value)

function Drilldown({pivot,rowKey,columnKey,onClose}:{pivot:Pivot;rowKey:string;columnKey:string;onClose:()=>void}){
  const [offset,setOffset]=useState(0),limit=100
  const result=useQuery({queryKey:['pivot-drilldown',pivot.id,rowKey,columnKey,offset],queryFn:()=>api<PivotDrilldownResult>(`/api/v1/pivots/${pivot.id}/drilldown?row_key=${encodeURIComponent(rowKey)}&column_key=${encodeURIComponent(columnKey)}&offset=${offset}&limit=${limit}`)})
  return <div className="pivot-drilldown" role="dialog" aria-modal="true" aria-label="피벗 원본 행"><header><div><Rows3/><span><strong>원본 행</strong><small>{result.data?.total.toLocaleString()??'…'}개 행 · {result.data?.source_range??pivot.source_range}</small></span></div><button aria-label="원본 행 닫기" onClick={onClose}>×</button></header><div className="pivot-table-wrap">{result.isLoading?<p className="pivot-loading">원본 행을 불러오는 중…</p>:<table><thead><tr><th>원본 행</th>{result.data?.headers.map((header,index)=><th key={`${header}-${index}`}>{header}</th>)}</tr></thead><tbody>{result.data?.rows.map(row=><tr key={row.source_row}><th>{row.source_row}</th>{row.values.map((value,index)=><td key={index}>{display(value)}</td>)}</tr>)}</tbody></table>}</div><footer><button className="secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))}>이전</button><span>{offset+1}–{Math.min(offset+limit,result.data?.total??offset+limit)}</span><button className="secondary" disabled={!result.data?.next_offset} onClick={()=>setOffset(result.data?.next_offset??offset)}>다음</button></footer></div>
}

export function PivotResultDialog({pivot,version,onClose,onRefresh}:{pivot:Pivot;version:number;onClose:()=>void;onRefresh:(pivot:Pivot)=>Promise<void>}){
  const client=useQueryClient(),[refreshing,setRefreshing]=useState(false),[drill,setDrill]=useState<{rowKey:string;columnKey:string}>()
  const result=useQuery({queryKey:['pivot-data',pivot.id,version],queryFn:()=>api<PivotData>(`/api/v1/pivots/${pivot.id}/data`)})
  const refresh=async()=>{setRefreshing(true);try{await onRefresh(pivot);await client.invalidateQueries({queryKey:['pivot-data',pivot.id]})}catch(error){alert(error instanceof Error?error.message:'피벗을 갱신하지 못했습니다.')}finally{setRefreshing(false)}}
  const dimensions=result.data?.pivot.rows.length??0
  const dialog=useDialog<HTMLElement>(onClose)
  return <div className="modal-backdrop"><div className="modal pivot-result-dialog" role="dialog" ref={dialog as React.RefObject<any>} aria-modal="true" aria-label="피벗 결과"><header><div><Table2/><span><h2>{result.data?.pivot.name??pivot.name}</h2><p>{result.data?.source_row_count.toLocaleString()??'…'}개 원본 행 · {result.data?.cached?'캐시 결과':'실시간 결과'} · 소스 v{result.data?.source_version??pivot.source_version}</p>{result.data?.stale?<p className="pivot-stale"><AlertTriangle/> 원본이 바뀌었습니다 · 지금 갱신하면 반영됩니다</p>:null}</span></div><div><button className="secondary" disabled={refreshing||pivot.source_range==='#REF!'} onClick={()=>void refresh()}><RefreshCw className={refreshing?'spin':''}/> 지금 갱신</button><button aria-label="피벗 결과 닫기" onClick={onClose}>×</button></div></header>{result.data?.warning&&<div className="pivot-warning">원본 범위를 사용할 수 없습니다: {result.data.warning}</div>}<div className="pivot-table-wrap">{result.isLoading?<p className="pivot-loading">피벗 결과를 계산하는 중…</p>:result.isError?<p className="pivot-error">피벗 결과를 불러오지 못했습니다.</p>:<table><thead><tr>{Array.from({length:Math.max(1,dimensions)},(_,index)=><th key={index}>{result.data?.pivot.rows[index]?.name||result.data?.source_headers[(result.data?.pivot.rows[index]?.column??1)-1]||'행'}</th>)}{result.data?.columns.map(column=><th key={column.key}>{[...(column.labels??[]),column.value_name].filter(Boolean).join(' · ')}</th>)}</tr></thead><tbody>{result.data?.rows.map(row=><tr key={row.key}>{((row.labels??[]).length?row.labels:['전체']).map((label,index)=><th key={index}>{label}</th>)}{Array.from({length:Math.max(0,dimensions-(row.labels??[]).length)},(_,index)=><th key={`blank-${index}`}/>) }{row.values.map((value,index)=><td key={index}><button title="원본 행 보기" onClick={()=>setDrill({rowKey:row.key,columnKey:result.data!.columns[index].key})}>{display(value)}</button></td>)}</tr>)}{result.data&&<tr className="grand-total"><th colSpan={Math.max(1,dimensions)}>전체 합계</th>{result.data.grand_totals.map((value,index)=><td key={index}>{display(value)}</td>)}</tr>}</tbody></table>}</div><footer><span>결과 셀을 누르면 집계에 포함된 원본 행을 확인할 수 있습니다.</span><button className="primary" onClick={onClose}>닫기</button></footer>{drill&&<Drilldown pivot={result.data?.pivot??pivot} rowKey={drill.rowKey} columnKey={drill.columnKey} onClose={()=>setDrill(undefined)}/>}</div></div>
}
