import { useQuery } from '@tanstack/react-query'
import { Calculator, Plus, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { api } from '../lib/api'
import type { Cell, Pivot, PivotAggregation, PivotCalculatedField, PivotDimension, PivotFilter, PivotGroup, PivotValueField, Sheet } from '../types'
import './PivotDialog.css'
import { useDialog } from '../lib/useDialog'

type Draft={name:string;sourceSheetId:string;sourceRange:string;firstRowHeaders:boolean;rows:PivotDimension[];columns:PivotDimension[];values:PivotValueField[];filters:PivotFilter[];calculatedFields:PivotCalculatedField[];refreshMode:'auto'|'manual'}
const validCell=(value:string)=>/^[A-Z]+[1-9]\d*$/i.test(value.trim().replaceAll('$',''))
const validRange=(value:string)=>{const parts=value.split(':');return parts.length>0&&parts.length<=2&&parts.every(validCell)}
const columnNumber=(letters:string)=>[...letters.toUpperCase()].reduce((value,letter)=>value*26+letter.charCodeAt(0)-64,0)
const rangeShape=(value:string)=>{const match=/^([A-Z]+)([1-9]\d*)(?::([A-Z]+)([1-9]\d*))?$/i.exec(value.trim().replaceAll('$',''));if(!match)return;const startColumn=columnNumber(match[1]),endColumn=columnNumber(match[3]??match[1]);return{startRow:Number(match[2]),startColumn,width:endColumn-startColumn+1}}
const draftFor=(pivot:Pivot|undefined,activeSheetId:string,selectionRange:string):Draft=>pivot?{name:pivot.name,sourceSheetId:pivot.source_sheet_id??activeSheetId,sourceRange:pivot.source_range,firstRowHeaders:pivot.first_row_headers,rows:pivot.rows??[],columns:pivot.columns??[],values:pivot.values??[],filters:pivot.filters??[],calculatedFields:pivot.calculated_fields??[],refreshMode:pivot.refresh_mode}:{name:'새 피벗 테이블',sourceSheetId:activeSheetId,sourceRange:selectionRange,firstRowHeaders:true,rows:[],columns:[],values:[{column:1,aggregation:'sum'}],filters:[],calculatedFields:[],refreshMode:'auto'}
const groups:Array<[PivotGroup,string]>=[['none','그룹 없음'],['year','연도'],['quarter','분기'],['month','월'],['day','일'],['number','숫자 구간'],['custom','사용자 그룹']]
const aggregations:Array<[PivotAggregation,string]>=[['sum','합계'],['average','평균'],['count','개수'],['min','최소'],['max','최대']]
const operators:Array<[PivotFilter['operator'],string]>=[['equals','같음'],['not_equals','같지 않음'],['contains','포함'],['greater_than','보다 큼'],['greater_or_equal','이상'],['less_than','보다 작음'],['less_or_equal','이하'],['in','목록에 포함'],['is_blank','빈 값'],['not_blank','빈 값 아님']]
const customText=(dimension:PivotDimension)=>(dimension.custom_groups??[]).map(group=>`${group.name}=${group.values.join(',')}`).join('; ')
const parseCustom=(value:string)=>value.split(';').map(group=>group.trim()).filter(Boolean).map(group=>{const [name,...rest]=group.split('=');return{name:name.trim(),values:rest.join('=').split(',').map(item=>item.trim()).filter(Boolean)}}).filter(group=>group.name&&group.values.length)

export function PivotDialog({pivot,activeSheetId,selectionRange,sheets,onClose,onCreate,onUpdate,onDelete}:{
  pivot?:Pivot;activeSheetId:string;selectionRange:string;sheets:Sheet[];onClose:()=>void
  onCreate:(input:Record<string,unknown>)=>Promise<Pivot>;onUpdate:(pivot:Pivot,input:Record<string,unknown>)=>Promise<Pivot>;onDelete:(pivot:Pivot)=>Promise<void>
}){
  const [draft,setDraft]=useState(()=>draftFor(pivot,activeSheetId,selectionRange)),[saving,setSaving]=useState(false)
  useEffect(()=>setDraft(draftFor(pivot,activeSheetId,selectionRange)),[pivot,activeSheetId,selectionRange])
  const shape=rangeShape(draft.sourceRange)
  const source=useQuery({queryKey:['pivot-source-preview',draft.sourceSheetId,draft.sourceRange],queryFn:()=>api<{items:Cell[]}>(`/api/v1/sheets/${draft.sourceSheetId}/ranges/${draft.sourceRange.toUpperCase()}`),enabled:Boolean(draft.sourceSheetId&&validRange(draft.sourceRange))})
  const fields=useMemo(()=>Array.from({length:shape?.width??1},(_,index)=>{const absolute=(shape?.startColumn??1)+index,header=source.data?.items.find(cell=>cell.row===shape?.startRow&&cell.column===absolute)?.value;return{column:index+1,label:draft.firstRowHeaders&&header!=null?String(header):`열 ${index+1}`}}),[draft.firstRowHeaders,shape?.startColumn,shape?.startRow,shape?.width,source.data?.items])
  const fieldOptions=(value:number)=><>{fields.map(field=><option key={field.column} value={field.column}>{field.label} · {field.column}열</option>)}{!fields.some(field=>field.column===value)&&<option value={value}>{value}열</option>}</>
  const patch=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}))
  const patchDimension=(kind:'rows'|'columns',index:number,value:Partial<PivotDimension>)=>patch(kind,draft[kind].map((item,itemIndex)=>itemIndex===index?{...item,...value}:item))
  const save=async()=>{if(!validRange(draft.sourceRange)||!draft.name.trim())return;setSaving(true);try{
    const fieldName=(column:number)=>fields.find(field=>field.column===column)?.label??`열 ${column}`
    const dimensions=(items:PivotDimension[])=>items.map(item=>({...item,name:item.name?.trim()||fieldName(item.column)}))
    const values=draft.values.map(item=>({...item,name:item.name?.trim()||`${aggregations.find(([value])=>value===item.aggregation)?.[1]??item.aggregation} ${fieldName(item.column)}`}))
    const input={sheet_id:pivot?.sheet_id??activeSheetId,source_sheet_id:draft.sourceSheetId,name:draft.name.trim(),source_range:draft.sourceRange.toUpperCase(),first_row_headers:draft.firstRowHeaders,rows:dimensions(draft.rows),columns:dimensions(draft.columns),values,filters:draft.filters,calculated_fields:draft.calculatedFields,refresh_mode:draft.refreshMode};if(pivot)await onUpdate(pivot,{...input,expected_revision:pivot.revision});else await onCreate(input);onClose()
  }catch(error){alert(error instanceof Error?error.message:'피벗을 저장하지 못했습니다.')}finally{setSaving(false)}}
  const remove=async()=>{if(!pivot||!confirm('이 피벗 테이블을 삭제할까요?'))return;setSaving(true);try{await onDelete(pivot);onClose()}catch(error){alert(error instanceof Error?error.message:'피벗을 삭제하지 못했습니다.')}finally{setSaving(false)}}
  const dialog=useDialog<HTMLElement>(onClose)
  return <div className="modal-backdrop"><div className="modal pivot-dialog" role="dialog" ref={dialog as React.RefObject<any>} aria-modal="true" aria-label={pivot?'피벗 편집':'피벗 만들기'}>
    <header><div><Calculator/><div><h2>{pivot?'피벗 편집':'피벗 만들기'}</h2><p>원본은 유지하고 관리형 정의와 계산 결과를 별도로 저장합니다.</p></div></div><button aria-label="피벗 대화상자 닫기" onClick={onClose}>×</button></header>
    <section>
      <div className="pivot-fields three"><label>이름<input aria-label="피벗 이름" maxLength={200} value={draft.name} onChange={event=>patch('name',event.target.value)}/></label><label>원본 시트<select aria-label="피벗 원본 시트" value={draft.sourceSheetId} onChange={event=>patch('sourceSheetId',event.target.value)}>{sheets.map(sheet=><option value={sheet.id} key={sheet.id}>{sheet.name}</option>)}</select></label><label>원본 범위<input aria-label="피벗 원본 범위" value={draft.sourceRange} onChange={event=>patch('sourceRange',event.target.value)} placeholder="A1:F100"/></label></div>
      <div className="pivot-options"><label><input type="checkbox" checked={draft.firstRowHeaders} onChange={event=>patch('firstRowHeaders',event.target.checked)}/> 첫 행을 필드 이름으로 사용</label><label>갱신<select aria-label="피벗 갱신 방식" value={draft.refreshMode} onChange={event=>patch('refreshMode',event.target.value as 'auto'|'manual')}><option value="auto">원본 변경 시 자동</option><option value="manual">수동 갱신</option></select></label></div>
      <div className="pivot-config-grid">
        {(['rows','columns'] as const).map(kind=><fieldset key={kind}><legend>{kind==='rows'?'행 그룹':'열 그룹'} <button aria-label={`${kind==='rows'?'행':'열'} 그룹 추가`} disabled={draft.rows.length+draft.columns.length>=6} onClick={()=>patch(kind,[...draft[kind],{column:1,group:'none'}])}><Plus/></button></legend>{draft[kind].length===0?<small>설정하지 않음</small>:draft[kind].map((item,index)=><div className="pivot-rule dimension" key={`${kind}-${index}`}><select aria-label={`${kind} 필드 ${index+1}`} value={item.column} onChange={event=>patchDimension(kind,index,{column:Number(event.target.value)})}>{fieldOptions(item.column)}</select><select aria-label={`${kind} 그룹 ${index+1}`} value={item.group??'none'} onChange={event=>patchDimension(kind,index,{group:event.target.value as PivotGroup})}>{groups.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{item.group==='number'&&<input aria-label="숫자 그룹 간격" type="number" min="0.000001" value={item.interval??10} onChange={event=>patchDimension(kind,index,{interval:Number(event.target.value)})}/>} {item.group==='custom'&&<input className="wide" aria-label="사용자 그룹" value={customText(item)} onChange={event=>patchDimension(kind,index,{custom_groups:parseCustom(event.target.value)})} placeholder="핵심=A,B; 기타=C,D"/>}<button aria-label="그룹 삭제" onClick={()=>patch(kind,draft[kind].filter((_,itemIndex)=>itemIndex!==index))}>×</button></div>)}</fieldset>)}
        <fieldset><legend>값 <button aria-label="값 추가" disabled={draft.values.length>=10} onClick={()=>patch('values',[...draft.values,{column:1,aggregation:'sum'}])}><Plus/></button></legend>{draft.values.map((item,index)=><div className="pivot-rule" key={`value-${index}`}><select aria-label={`값 필드 ${index+1}`} value={item.column} onChange={event=>patch('values',draft.values.map((value,itemIndex)=>itemIndex===index?{...value,column:Number(event.target.value)}:value))}>{fieldOptions(item.column)}</select><select aria-label={`집계 ${index+1}`} value={item.aggregation} onChange={event=>patch('values',draft.values.map((value,itemIndex)=>itemIndex===index?{...value,aggregation:event.target.value as PivotAggregation}:value))}>{aggregations.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input aria-label={`값 이름 ${index+1}`} value={item.name??''} onChange={event=>patch('values',draft.values.map((value,itemIndex)=>itemIndex===index?{...value,name:event.target.value}:value))} placeholder="표시 이름"/><button disabled={draft.values.length===1} aria-label="값 삭제" onClick={()=>patch('values',draft.values.filter((_,itemIndex)=>itemIndex!==index))}>×</button></div>)}</fieldset>
        <fieldset><legend>필터 <button aria-label="필터 추가" disabled={draft.filters.length>=10} onClick={()=>patch('filters',[...draft.filters,{column:1,operator:'equals',value:''}])}><Plus/></button></legend>{draft.filters.length===0?<small>모든 원본 행을 포함합니다.</small>:draft.filters.map((item,index)=><div className="pivot-rule" key={`filter-${index}`}><select aria-label={`필터 필드 ${index+1}`} value={item.column} onChange={event=>patch('filters',draft.filters.map((value,itemIndex)=>itemIndex===index?{...value,column:Number(event.target.value)}:value))}>{fieldOptions(item.column)}</select><select aria-label={`필터 조건 ${index+1}`} value={item.operator} onChange={event=>patch('filters',draft.filters.map((value,itemIndex)=>itemIndex===index?{...value,operator:event.target.value as PivotFilter['operator']}:value))}>{operators.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{!['is_blank','not_blank'].includes(item.operator)&&<input aria-label={`필터 값 ${index+1}`} value={item.operator==='in'?(item.values??[]).join(','):item.value??''} onChange={event=>patch('filters',draft.filters.map((value,itemIndex)=>itemIndex===index?{...value,...(item.operator==='in'?{values:event.target.value.split(',').map(entry=>entry.trim()).filter(Boolean)}:{value:event.target.value})}:value))} placeholder={item.operator==='in'?'쉼표로 구분':'비교 값'}/>}<button aria-label="필터 삭제" onClick={()=>patch('filters',draft.filters.filter((_,itemIndex)=>itemIndex!==index))}>×</button></div>)}</fieldset>
        <fieldset><legend>계산 필드 <button aria-label="계산 필드 추가" disabled={draft.calculatedFields.length>=5} onClick={()=>patch('calculatedFields',[...draft.calculatedFields,{name:'',formula:'=V1'}])}><Plus/></button></legend>{draft.calculatedFields.length===0?<small>V1, V2…로 값 집계를 참조할 수 있습니다.</small>:draft.calculatedFields.map((item,index)=><div className="pivot-rule calculated" key={`calculated-${index}`}><input aria-label={`계산 필드 이름 ${index+1}`} value={item.name} onChange={event=>patch('calculatedFields',draft.calculatedFields.map((value,itemIndex)=>itemIndex===index?{...value,name:event.target.value}:value))} placeholder="단가"/><input aria-label={`계산 필드 수식 ${index+1}`} value={item.formula} onChange={event=>patch('calculatedFields',draft.calculatedFields.map((value,itemIndex)=>itemIndex===index?{...value,formula:event.target.value}:value))} placeholder="=V1/V2"/><button aria-label="계산 필드 삭제" onClick={()=>patch('calculatedFields',draft.calculatedFields.filter((_,itemIndex)=>itemIndex!==index))}>×</button></div>)}</fieldset>
      </div>
    </section>
    <div className="modal-actions pivot-actions">{pivot&&<button className="danger" disabled={saving} onClick={remove}><Trash2/> 삭제</button>}<span/><button className="secondary" onClick={onClose}>취소</button><button className="primary" disabled={saving||!draft.name.trim()||!validRange(draft.sourceRange)||draft.values.length===0} onClick={save}>{saving?'저장 중…':'피벗 저장'}</button></div>
  </div></div>
}
