import { useState } from 'react'
import type { MergeRange } from '../lib/merge'
import type { SortKey,SortOptions } from '../lib/sort'
import { useDialog } from '../lib/useDialog'

function columnName(column:number){let value=column,result='';while(value>0){value-=1;result=String.fromCharCode(65+value%26)+result;value=Math.floor(value/26)}return result}

export function SortDialog({range,onClose,onSort}:{range:MergeRange;onClose:()=>void;onSort:(options:SortOptions)=>Promise<void>}){
  const columns=Array.from({length:range.endColumn-range.startColumn+1},(_,index)=>range.startColumn+index)
  const [keys,setKeys]=useState<SortKey[]>([{column:range.startColumn,direction:'asc'}]),[header,setHeader]=useState(range.endRow-range.startRow>=2),[caseSensitive,setCaseSensitive]=useState(false),[literalOrder,setLiteralOrder]=useState(false),[saving,setSaving]=useState(false)
  const update=(index:number,patch:Partial<SortKey>)=>setKeys(current=>current.map((key,keyIndex)=>keyIndex===index?{...key,...patch}:key))
  const submit=async()=>{if(new Set(keys.map(key=>key.column)).size!==keys.length)return alert('정렬 기준 열은 중복될 수 없습니다.');setSaving(true);try{await onSort({keys,headerRows:header?1:0,caseSensitive,literalOrder});onClose()}catch{/* sortSelection displays the validation message and keeps this dialog open. */}finally{setSaving(false)}}
  const dialog=useDialog<HTMLElement>(onClose)
  return <div className="modal-backdrop"><div className="modal sort-modal" role="dialog" ref={dialog as React.RefObject<any>} aria-modal="true" aria-label="범위 정렬"><h2>범위 정렬</h2><p>{columnName(range.startColumn)}{range.startRow}:{columnName(range.endColumn)}{range.endRow} 범위를 위에서부터 순서대로 정렬합니다.</p><label className="sort-check"><input type="checkbox" checked={header} onChange={event=>setHeader(event.target.checked)}/> 첫 행을 헤더로 고정</label><div className="sort-keys">{keys.map((key,index)=><div className="sort-key" key={index}><span>{index===0?'우선 기준':`${index+1}차 기준`}</span><select aria-label={`${index+1}차 정렬 열`} value={key.column} onChange={event=>update(index,{column:Number(event.target.value)})}>{columns.map(column=><option key={column} value={column}>{columnName(column)}열</option>)}</select><select aria-label={`${index+1}차 정렬 방향`} value={key.direction} onChange={event=>update(index,{direction:event.target.value as SortKey['direction']})}><option value="asc">오름차순</option><option value="desc">내림차순</option></select>{keys.length>1&&<button aria-label={`${index+1}차 정렬 기준 삭제`} onClick={()=>setKeys(current=>current.filter((_,keyIndex)=>keyIndex!==index))}>×</button>}</div>)}</div><div className="sort-options"><button className="secondary" disabled={keys.length>=columns.length} onClick={()=>{const used=new Set(keys.map(key=>key.column)),column=columns.find(candidate=>!used.has(candidate));if(column)setKeys(current=>[...current,{column,direction:'asc'}])}}>+ 기준 추가</button><label className="sort-check"><input type="checkbox" checked={caseSensitive} onChange={event=>setCaseSensitive(event.target.checked)}/> 대소문자 구분</label><label className="sort-check" title="끄면 글자 그대로 견줍니다. 10월이 1월보다 앞에 옵니다."><input type="checkbox" checked={literalOrder} onChange={event=>setLiteralOrder(event.target.checked)}/> 숫자를 글자로 취급</label></div><div className="modal-actions"><button className="secondary" onClick={onClose}>취소</button><button className="primary" disabled={saving||range.endRow-range.startRow+1-(header?1:0)<2} onClick={submit}>{saving?'정렬 중…':'정렬 적용'}</button></div></div></div>
}
